env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - simple-import-sort
  - '@typescript-eslint'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
rules:
  arrow-body-style:
    - error
    - as-needed
  no-console: error
  no-unused-vars: 'off'
  import/prefer-default-export: 'off'
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  simple-import-sort/imports:
    - error
    - groups:
        - - '^react'
          - "^@?\\w"
        - - '^(components|modules|utils)(/.*|$)'
        - - "^\\u0000"
        - - "^\\.\\.(?!/?$)"
          - "^\\.\\./?$"
        - - "^\\./(?=.*/)(?!/?$)"
          - "^\\.(?!/?$)"
          - "^\\./?$"
        - - "^.+\\.?(css)$"
