env:
  browser: true
  es2021: true
extends:
  - '@mkappelhof/eslint-config-base'
  - plugin:react/recommended
rules:
  react-hooks/exhaustive-deps: 'off'
  react/boolean-prop-naming:
    - error
    - propTypeNames:
        - bool
      rule: '^(is|has)[A-Z]([A-Za-z0-9]?)+'
  react/destructuring-assignment:
    - warn
    - always
  react/function-component-definition:
    - warn
    - namedComponents: arrow-function
  react/hook-use-state:
    - error
    - allowDestructuredState: true
  react/jsx-handler-names: warn
  react/jsx-key: warn
  react/jsx-max-depth:
    - warn
    - max: 4
  react/jsx-no-constructed-context-values: error
  react/jsx-no-useless-fragment: error
  react/jsx-curly-brace-presence:
    - error
    - props: never
      children: never
  react/prop-types: 'off'
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/jsx-uses-react: 'off'
  react/no-multi-comp: error
  react/react-in-jsx-scope: 'off'
  react/require-default-props: 'off'
