on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile --immutable
        working-directory: ./

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
        id: changesets
        uses: changesets/action@v1
        with:
          title: Upcoming Release Changes
          commit: "chore(release): release packages versions"
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
